require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - log/**/*
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - Rakefile
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config/**/*
    - scripts/**/*
    - Gemfile
    - spec/support/*
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.1.3

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/ParameterLists:
  Max: 10

Metrics/MethodLength:
  Max: 30
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 150
  Exclude:
    - app/models/**/*

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*
    - lib/tasks/*
    - app/admin/*

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - spec/docs/**/*

Naming/MethodParameterName:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
